### PR TITLE
Add `SHLVL` item

### LINKED ISSUE #156: Add a `SHLVL` module
#### Is your feature request related to a problem? Please describe

I would like to propose a `SHLVL` module to display current `$SHLVL` if it exceeds a configurable threshold.

This is really handy if one frequently works with nested shells (or people loving to tinker around like me 😀).

#### Describe the solution you'd like

Something like:

```fish
function _tide_shlvl
  if test $SHLVL -gt $tide_shlvl_threshold
    echo ↕️ $SHLVL
  end
end
```

#### Additional context

Powerlevel10k doesn't have this (AKAIK) but [Starship does](https://starship.rs/config/#shlvl).

### PR DESCRIPTION
**Pull request by kidonng**
#### Description

Add a new item: `SHLVL`

~~Checks [fails on macOS](https://github.com/kidonng/tide/runs/2867992159?check_suite_focus=true) because of fish-actions/littlecheck#1~~

#### Motivation and Context

Close #156

#### Screenshots (if appropriate)

image

#### How Has This Been Tested

- [ ] I have tested using **Linux**.
- [x] I have tested using **MacOS**.

#### Checklist

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by IlanCosman** [comment]
I'll get the littlecheck item fixed, and then merge this 👍

**Comment by kidonng** [comment]
On macOS CI the shell starts with two levels deeper (i.e. starting from 3 rather than 1). Sorry if I'm wrong but looks like littlecheck doesn't support conditions, so we either run the test on one OS only or write tests for each system.

**Comment by IlanCosman** [comment]
What's the reasoning behind having a configurable threshold? Why not just 2?

**Comment by kidonng** [comment]
> > On macOS CI the shell starts with two levels deeper (i.e. starting from 3 rather than 1).
> 
> Good to know 😄

I only got to know that from the CI failures.

> What's the reasoning behind having a configurable threshold? Why not just 2?

The macOS CI is a perfect example (also read the original feature request): depending on your environment you may start will a different `$SHLVL` and hard-coding it doesn't make sense.

**Comment by IlanCosman** [comment]
> The macOS CI is a perfect example (also read the original feature request): depending on your environment you may start with a different $SHLVL and hard-coding it doesn't make sense.

I thought that might be a peculiarity of the CI. My mac starts with `SHLVL` 1, but I suppose I have seen other environments 👍

**Comment by IlanCosman** [comment]
Thanks for contributing 😄

**Comment by kidonng** [comment]
You are welcome! I plan to add more items later: `private_mode`, `nix_shell` and `nodejs`.
I have also updated the wiki to reflect the changes. Please make sure to review and edit them to your liking!

**Pull request merged**
