### PR TITLE
Add chruby

### PR DESCRIPTION
**Pull request by pusewicz**
Supersedes https://github.com/IlanCosman/tide/pull/92.

Being more explicit about the item (and the tools it is using) is better for the experience.

Users then can add whatever tool they use, such as `rbenv` or `rvm` as separate items.

### CODE REVIEW

**Comment by pusewicz** [comment]
Wiki documentation:

```
## chruby

| Variable        | Description                                | Type    |
| --------------- | -------------------------------------------| ------- |
| bg_color        | background color of chruby item            | color   |
| color           | color of chruby item                       | color   |
| icon            | icon to display next to the chruby version | string  |
```

**Comment by pusewicz** [comment]
I've rebased against main @IlanCosman.

**Review by IlanCosman — CHANGES_REQUESTED** [review]
There are a few copy-paste errors, like deleting the `tide_rust.*` variables in the classic config. Also, you added in a `tide_chruby_verbose_version` that doesn't exist 😄

**Review by IlanCosman — CHANGES_REQUESTED** [review]
Also, please add `chruby` to the `tide_right_prompt_items` list in each config, since it will now be automatically removed if `type -q chruby` fails.

**Comment by pusewicz** [comment]
@IlanCosman Done!

**Comment by IlanCosman** [comment]
@pusewicz Can I ask how you're using `chruby` through fish? I'd like to test it out in the wild.

**Comment by pusewicz** [comment]
Sure, I use it on macOS via Homebrew install of https://github.com/JeanMertz/chruby-fish.

Just follow the instructions.

Then install different ruby versions via https://github.com/sstephenson/ruby-build#readme.

**Comment by IlanCosman** [comment]
Bah I'm too lazy 😂 Do you know the difference between `RUBY_AUTO_VERSION` and `RUBY_VERSION`?

**Review by IlanCosman — APPROVED** [review]

**Comment by IlanCosman** [comment]
Thanks for your contribution @pusewicz 😄

**Comment by IlanCosman** [comment]
Oh @pusewicz, can you add the chruby variable documentation to the wiki? Kind of annoying that it isn't better integrated.

**Comment by pusewicz** [comment]
@IlanCosman Done!

**Pull request merged**
