### PR TITLE
Add support for Bun

### PR DESCRIPTION
**Pull request by will-stone**
#### Description

Support [bun](https://bun.sh/) JS runtime. When a bun lockfile is detected, it'll display the Bun version (with an oven icon) along with Bun's version.

#### Motivation and Context

Closes https://github.com/IlanCosman/tide/issues/484 

#### How Has This Been Tested

I currently cannot seem to get this working. But maybe I'm setting something-up incorrectly.

- [ ] I have tested using **Linux**.
- [ ] I have tested using **MacOS**.

#### Checklist

- [ ] I am ready to update the wiki accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by IlanCosman** [comment]
I undid the administrative stuff you did (leave that to me 😄), and I'm also not currently going to be making the node item not display when bun does. But the items works fine for me, I get a nice off-white version number with an oven icon. Really not sure why you're having problems.

**Comment by will-stone** [comment]
Oh great 😄 Well, if you do a release I'll let you know, and we can fix through bug fixes if it's still not working for me.

**Comment by will-stone** [comment]
I installed my version using Fisher: `fisher install will-stone/tide@add-support-for-bun` and it worked 🥳 Looks like this is ready to go.

CleanShot 2024-01-28 at 2  02 13@2x

**Comment by jorgebucaran** [comment]
Thank you, @will-stone! 💯

**Pull request merged**
