### PR TITLE
Add tide prompt item GO similiar to RUST support

### PR DESCRIPTION
**Pull request by dr-emacs**
#### Description

Added prompt item for GO indicating go version number and small gopher icon

#### How Has This Been Tested

- [ X ] I have tested using **Linux**.
- [ ] I have tested using **MacOS**.

#### Checklist

- [ ] I have updated the documentation accordingly.
- [ X ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by IlanCosman** [comment]
Great work 👍 Merged into the `v5` branch with a few small tweaks. Thanks for contributing 😄

**Comment by dr-emacs** [comment]
Thank you! My first pull reuest ...
When exchanging the gopher icon in my second commit I noticed a very strange behaviour. Somehow the writing direction seems to switch to left to right. At least this improved only after switching from  a numeric only 1.16.5 to go1.16.5.
Maybe you have got en idea?

I'm currently planning to implement a prompt item showing the current battery level. Would that be interesting too?

**Comment by IlanCosman** [comment]
> When exchanging the gopher icon in my second commit I noticed a very strange behaviour. Somehow the writing direction seems to switch to left to right. At least this improved only after switching from a numeric only 1.16.5 to go1.16.5.

I noticed that too, so I just used a different gopher icon 😂 No idea why that specific character is weird.

> I'm currently planning to implement a prompt item showing the current battery level. Would that be interesting too?

Sure! I think it might be a difficult though with different operating systems and whatnot 😄

**Comment by dr-emacs** [comment]
I am only able to test on Linux. I think I'll have to check for the linux specific /sys/class/power_supply. Maybe somebody else will be able to pick up from there ...
Are there more  missing/needed prompt items?
I switched from ksh to bash to zsh to fish and used by current IP, battery level, free memory, CPU temperature, system load.

**Comment by IlanCosman** [comment]
If you're really interested in slaving away 😄 then [Spacefish](https://github.com/matchai/spacefish/tree/master/functions) has a bunch of items that might be nice to port over. Specifically, kubectl has been requested for Tide in the past. 

As for the ones you mentioned, I don't find them useful, and they're probably fairly annoying to implement due to the aforementioned OS issue, but if you want to, go ahead 😄

**Pull request closed without merging**
