### PR TITLE
add `nix_shell` item

### PR DESCRIPTION
**Pull request by oati**
#### Description

This PR adds the prompt item `nix_shell`, which checks and displays the `IN_NIX_SHELL` environment variable.

#### Motivation and Context

This makes the prompt display the shell status of Nix development environments.

#### How Has This Been Tested

- [x] I have tested using **Linux**.
- [ ] I have tested using **MacOS**.

#### Checklist

(I have not tested the test files.)

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by IlanCosman** [comment]
Thanks for the PR! Could you give me some basic instructions on how to test this in the real world? I have `nix` and `nix-shell` etc installed. What would I do next to get into a nix shell and have the `IN_NIX_SHELL` variable appear?

**Comment by IlanCosman** [comment]
Thanks for the PR! Could you give me some basic instructions on how to test this in the real world? I have `nix` and `nix-shell` etc installed. What would I do next to get into a nix shell and have the `IN_NIX_SHELL` variable appear?

**Comment by deflock** [comment]
I guess you can test it by `nix-shell -p hello`

**Comment by oati** [comment]
> I guess you can test it by `nix-shell -p hello`

you might have to do `nix-shell -p hello --run fish`

I'll mostly be using this for `nix develop` with nix-direnv inside flake projects.

**Review by IlanCosman — APPROVED** [review]
lgtm, thanks for contributing :)

**Pull request merged**
