### PR TITLE
Add docker context item

### PR DESCRIPTION
**Pull request by Crocmagnon**
#### Description
Add an item displaying the current docker context. Largely inspired by the kubectl item.

#### Screenshots (if appropriate)

Screenshot 2021-12-05 at 20 36 24

#### How Has This Been Tested

- [x] I have tested using **Linux**.
- [x] I have tested using **MacOS**.

#### Checklist

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by IlanCosman** [comment]
Thanks! I'll take a look. Don't worry about mega-linter.

**Comment by IlanCosman** [comment]
Can you give me a quick run-down on how you tested this? I have everything set up, but I'm not very knowledgeable about docker.

**Comment by Crocmagnon** [comment]
Sure! With docker installed, you can list contexts using `docket context ls`. There should be at least one named `default`. If you use the default context, no output will be shown as with the kubectl item.
You can create a new context with another name and switch to using it, the item should then update.

Here’s Docker’s documentation about contexts including how to create and switch to a new context: https://docs.docker.com/engine/context/working-with-contexts/

**Comment by IlanCosman** [comment]
Found a problem. `docker context show` isn't available with normal docker, it requires docker-compose. You can switch this item to using `docker context ls` or `docker context inspect` at your discretion.

**Comment by Crocmagnon** [comment]
Done 👍🏻

**Comment by IlanCosman** [comment]
Thanks, looks pretty good 👍 I'll get back to this in a few days, I need to study for finals 😄

**Comment by IlanCosman** [comment]
I'm a bit concerned about performance 😞 Even with async, I'm not super excited about 20-40 ms extra (on my machines). 

`kubectl` has garbage performance, but I'm more ok with that because fewer people use it.

**Comment by Crocmagnon** [comment]
Well, considering that docker contexts are kind of a power user feature, and power users are very likely to also have docker compose, and IIRC, compose is now bundled into docker (it’s now available as a subcommand `docker compose` instead of a separate `docker-compose`) ; would it be ok to revert to the previous better performing version of the item (with context show)?

**Comment by IlanCosman** [comment]
> Well, considering that docker contexts are kind of a power user feature, and power users are very likely to also have docker compose, and IIRC, compose is now bundled into docker (it’s now available as a subcommand docker compose instead of a separate docker-compose) ; would it be ok to revert to the previous better performing version of the item (with context show)?

Just tried it out. `docker compose` is only available _after_ you've installed `docker-compose`. So not really bundled together.
And I haven't gotten `docker context show` to work at all, even with docker compose installed. 

"docker context show" on google gives very few results, and no official documentation.

---

I think that we should follow what spacefish and starship are doing here, which is only running the item if some files exist.
From Starship:

detect_files | ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"] | Which filenames should trigger this module (needs only_with_files to be true).
-- | -- | --

Could you add that? Don't make it configurable though.

**Comment by Crocmagnon** [comment]
Yeah, I couldn't find any official documentation on `docker context show`, but I found it in the github issue template on the official compose-cli repository though (https://github.com/docker/compose-cli/issues/new).

Just for the record, I'm currently using version 20.10.11 of Docker Desktop for Mac. The same version on linux doesn't seem to offer `docker context show` indeed.

Anyway, I tried with `docker context ls | grep "*" | cut -f 1 -d '*' | xargs` but it takes about the same time as the previous version (inspect + format).

I don't think limiting this to a repository containing some arbitrary files would be useful. As with k8s contexts, this affects docker commands globally.

**Comment by IlanCosman** [comment]
> I don't think limiting this to a repository containing some arbitrary files would be useful. As with k8s contexts, this affects docker commands globally.

Yes, it effects docker globally, but the question is when are you going to need to see it. 

The optimal solution AFAICT would be https://github.com/IlanCosman/tide/issues/90, where the docker context only shows up if your command line has `docker` in it.

We generally use the files as a proxy for that though. How often are you going to be running `docker` commands when there are no docker related files nearby? (I don't know the answer btw, I don't use docker 😄)

**Comment by Crocmagnon** [comment]
> How often are you going to be running docker commands when there are no docker related files nearby?

That's a very interesting question. Since I mostly use docker compose to run stuff with docker on my machine, I'd say that in this case I would nearly always have a compose or dockerfile nearby.
However, having recently discovered docker contexts, my use case is slightly different: I'm managing a remote server with docker installed and I want to access its docker daemon easily from my machine, to view logs for example. In this case, I don't think I'll have a compose file nearby, and that's when viewing the context would matter the most.

**Comment by IlanCosman** [comment]
> Is the detect_files function already implemented?

Yes, it's called [test](https://fishshell.com/docs/current/cmds/test.html) 😄

> In this case, I don't think I'll have a compose file nearby, and that's when viewing the context would matter the most.

Fair enough. Then let's not detect files, and just have this item not be on by default 👍 (so no changes necessary)

**Comment by IlanCosman** [comment]
5727ca353f70e3a79daf5176946acdd97d1b9410 Merged with some changes into the fish-3.4 branch 👍 Thanks for contributing 😄

**Comment by IlanCosman** [comment]
Oh, dang, it didn't give you credit for any of your commits. I'll try to fix that.

**Pull request closed without merging**
