### PR TITLE
Add an Elixir prompt Item

### PR DESCRIPTION
**Pull request by aselder**
#### Description

A simple prompt item to display the current elixir version. 

#### How Has This Been Tested

- [x] I have tested using **Linux**.
- [x] I have tested using **MacOS**.

#### Checklist

- [x] I am ready to update the wiki accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by aselder** [comment]
It looks like the failing test is not related to my changes

**Comment by IlanCosman** [comment]
Sorry, I'm just not in a position to be dealing with Tide right now. In a week I should be free, and I'll take a look then. Thanks for your patience, sorry for the delay.

**Comment by aselder** [comment]
@IlanCosman No worries. Let me know if there is anything I can do to help.

**Comment by IlanCosman** [comment]
Thanks for contributing 👍If you could add the relevant elixir variables to the wiki that would be appreciated 🙂

**Pull request merged**
