### PR TITLE
Check for negative value when printing prompt connection

### LINKED ISSUE #120: Negative value error in string repeat using prompt connections with long paths
#### Describe the bug

With prompt connection enabled and then navigating to a long path and resizing the terminal window too small, error is printed out.

#### Steps to reproduce

1. Navigate to a long path on the filesystem with prompt connection enabled
2. Resize terminal window small enough so there's no room to add prompt connection symbols
3. hit enter to see error

#### Expected behavior

When the window is too small, just avoid printing any connection symbols.

#### Screenshots

screenshot

#### Environment (please complete the following information)

- Operating System: NixOS 21.05pre (also shows up on MacOS)
- Output of `tide bug-report`:

```console
fish, version 3.2.0
tide, version 4.2.0
xterm-256color
```

### PR DESCRIPTION
**Pull request by mfossen**
#### Description

applies to issue #120 

Check for a negative value before printing prompt connection to avoid issues with `string repeat`.

#### Motivation and Context

Closes #120 

#### How Has This Been Tested

- [x] I have tested using **Linux**.
- [x] I have tested using **MacOS**.

This looks like it fixes the issue when I add it on both Linux and MacOS.

#### Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by IlanCosman** [comment]
Oh wait, that was stupid of me, let me test if that even works 😅

**Comment by IlanCosman** [comment]
Yah no that was just me being an idiot, your way is right 😂 I'll get this merged.

**Comment by mfossen** [comment]
> Yah no that was just me being an idiot, your way is right joy I'll get this merged.

No worries! Thought I missed something as well and tested it just in case :+1:

**Review by IlanCosman — APPROVED** [review]

**Comment by IlanCosman** [comment]
gah CI being annoying, gotta get that fixed first :(

**Comment by IlanCosman** [comment]
Thanks for contributing @mfossen 😄

**Pull request merged**
