### PR TITLE
Fix distrobox prompt support

### LINKED ISSUE #332: Distrobox distro indicator similar to powerlevel10k
#### Is your feature request related to a problem? Please describe

In Tide there is a indicator that displays if user currently work in Toolbox, but there is no that indicator for [Distrobox](https://github.com/89luca89/distrobox), it would be good to have this indicator, because now it imposible to know if you are in distrobox or not.

#### Describe the solution you'd like

Add a indicator similar to toolbox one

## Tide in Toolbox

Снимок экрана от 2022-08-21 20-00-35

## Tide in Distrobox (arch)

Снимок экрана от 2022-08-21 20-00-44

## Powerlevel10k in Distrobox (arch)

Снимок экрана от 2022-08-21 20-01-33

### PR DESCRIPTION
**Pull request by mt190502**
#### Fix distrobox prompt support
I recently installed distrobox. But I couldn't see a prompt that I'm in distrobox (like toolbox). I reviewed this page today. I recently saw that distrobox prompt support has been added #332. But it wasn't working for me. When I examined the codes, I noticed that there were deficiencies.
- /run/.distroboxenv file not found inside distrobox containers
- /usr/bin/distrobox file not found inside distrobox containers

Fixed this problem(s)

#### Motivation and Context

Closes #332

#### Screenshots (if appropriate)
image

#### How Has This Been Tested

- [x] I have tested using **Linux**.
- [ ] I have tested using **MacOS**.

#### Checklist

- [ ] I am ready to update the wiki accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by daudix-UFO** [comment]
Thank you!

**Comment by IlanCosman** [comment]
@mt190502 Thanks for catching these errors! I could have sworn I tested, but I guess I only tested toolbox and just thought I tested distrobox 😅 

I made some changes to clean up the code, could you verify that it works as expected?

**Comment by mt190502** [comment]
> @mt190502 Thanks for catching these errors! I could have sworn I tested, but I guess I only tested toolbox and just thought I tested distrobox sweat_smile
> 
> I made some changes to clean up the code, could you verify that it works as expected?

After a while I noticed something. If any script named distrobox-enter is created in $PATH, it breaks the process. I'll have to find a more dynamic method

**Comment by daudix-UFO** [comment]
> After a while I noticed something. If any script named distrobox-enter is created in $PATH, it breaks the process. I'll have to find a more dynamic method

Not sure if everyone have such script :D

**Comment by mt190502** [comment]
> > After a while I noticed something. If any script named distrobox-enter is created in $PATH, it breaks the process. I'll have to find a more dynamic method
> 
> Not sure if someone have such script :P

It could even be an alias. :grin: 
Sample:
/home/$USER/.local/bin/distrobox-enter
```
#!/bin/bash
/usr/bin/distrobox-enter distroname -- $HOME/.preloadscript
/usr/bin/distrobox-enter distroname
```

**Comment by daudix-UFO** [comment]
Oh, this makes more sense

**Comment by mt190502** [comment]
> Oh, this makes more sense

I did a lot of research inside the container. To see if there is a file belonging to Distrobox. Finally, I found the file named `/etc/profile.d/distrobox_profile.sh`. It would make much more sense to use this.

**Comment by mt190502** [comment]
Look this @daudix-UFO @IlanCosman 
https://github.com/IlanCosman/tide/pull/351/files#diff-284d7fb5d575e17bbb32ce1eca5d5213e306c78a26e0fcab8740c27c0a9eba04R2

**Review by IlanCosman — APPROVED** [review]

**Comment by IlanCosman** [comment]
Looks great, thanks @mt190502 :)

**Comment by mt190502** [comment]
You're welcome @IlanCosman ❤

**Pull request merged**
