### PR TITLE
Display toolbox name

### PR DESCRIPTION
**Pull request by jazzsnobeatcake**
#### Description

Displays the toolbox name instead of the word toolbox.

#### Motivation and Context
$hostname defaults to "toolbox" when inside a toolbox.
$tide_toolbox_icon already indicates we're in a toolbox. 
Displaying the toolbox name adds further context in multi-toolbox environments.

#### How Has This Been Tested

I tested this on Fedora Silverblue 36

- [x] I have tested using **Linux**.
- [ ] I have tested using **MacOS**.

#### Checklist

Unsure if these are applicable.

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by daudix-UFO** [comment]
This would be really useful 👍

**Comment by IlanCosman** [comment]
Hi, sorry for the delay on reviewing this. I haven't had access to a linux machine for a while, but will again soon.

**Comment by daudix-UFO** [comment]
No problem ;)

**Comment by IlanCosman** [comment]
Also, external commands like grep and cat should be replaced with fish builtins such as `string match` and redirection (`some_command <file.txt`). Makes the code much faster and more portable :)

**Pull request merged**
